NORTHWIND.WebMVC/Models/SupplierView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NORTHWIND.WebMVC.Models
{
    public class SupplierView
    {
        [Display(Name = "Supplier ID")]
        public int SupplierID { get; set; }

        [Required]
        [Display(Name = "Company Name")]
        public string CompanyName { get; set; }

        [Required]
        [Display(Name = "Contact Name")]
        public string ContactName { get; set; }

        [Required]
        [Display(Name = "Contact Title")]
        public string ContactTitle { get; set; }

        [Required]
        [Display(Name = "Address")]
        public string Address { get; set; }

        [Required]
        [Display(Name = "City")]
        public string City { get; set; }

        [Required]
        [Display(Name = "Region")]
        public string Region { get; set; }

        [Required]
        [Display(Name = "Postal Code")]
        public string PostalCode { get; set; }

        [Required]
        [Display(Name = "Country")]
        public string Country { get; set; }

        [Required]
        [Display(Name = "Phone")]
        public string Phone { get; set; }

        [Required]
        [Display(Name = "Fax")]
        public string Fax { get; set; }

        [Required]
        [Display(Name = "Home Page")]
        public string HomePage { get; set; }
    }
}

NORTHWIND.WebMVC/Controllers/SuppliersController.cs
using NORTHWIND.Common;
using NORTHWIND.Entity;
using NORTHWIND.Facade;
using NORTHWIND.WebMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NORTHWIND.WebMVC.Controllers
{
    public class SuppliersController : Controller
    {
        // GET: Suppliers
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Route("Paging")]
        public ActionResult Paging( PageData data)
        {
            var facade = new SupplierFacade();
            Dictionary<string, object> param = new Dictionary<string, object>();
            if (data.criteria != null)
                foreach (var crt in data.criteria)
                {
                    param[crt.criteria] = crt.value;
                }
            //query
            var rows = facade.GetListItemsByLikeCriteria(param, data.page, data.pageSize, data.order);
            var count = facade.GetListItemsByLikeCriteriaCount(param);
            var pageCount = Math.Ceiling(Commons.GetDouble(count) / data.pageSize);
            var apiResponse = ApiResponse.OK(new { rows = rows, rowCount = count, pageCount = pageCount });
            return Json(apiResponse);
        }

        // GET: Suppliers/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create()
        {
            return this.PartialView();
        }

        [HttpPost]
        public ActionResult CreateSave(SupplierView model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.PartialView("Create", model);
            }

            // todo db
            var facade = new SupplierFacade();
            var supplier = new Suppliers();
            //supplier.SupplierID = model.SupplierID;
            supplier.CompanyName = model.CompanyName;
            supplier.ContactName = model.ContactName;
            supplier.ContactTitle = model.ContactTitle;
            supplier.Address = model.Address;
            supplier.City = model.City;
            supplier.Region = model.Region;
            supplier.PostalCode = model.PostalCode;
            supplier.Country = model.Country;
            supplier.Phone = model.Phone;
            supplier.Fax = model.Fax;
            supplier.HomePage = model.HomePage;

            try
            {
                facade.Insert(supplier);
                return (ActionResult)this.Content(@"ok");
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(String.Empty, ex.Message);
            }
            return this.PartialView("Create", model);
        }


        //// POST: Suppliers/Create
        //[HttpPost]
        //public ActionResult Create(FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add insert logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: Suppliers/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Suppliers/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Suppliers/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Suppliers/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

NORTHWIND.WebMVC/Views/Suppliers/Create.cshtml
@model NORTHWIND.WebMVC.Models.SupplierView
@using (
    Ajax.BeginForm("CreateSave", "Suppliers", new AjaxOptions { HttpMethod = "POST", OnSuccess = "Apx.AjaxOnSuccess" }))
{
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <span class="close" data-dismiss="modal">&times;</span>
                <h4 class="modal-title" id="modalHeader">Create Customer</h4>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, String.Empty, new { @class = "text-danger" })
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(e => e.SupplierID, new { @class = "control-label col-md-3" })
                                <div class="col-md-6">
                                    @Html.EditorFor(e => e.SupplierID, String.Empty, new { htmlAttributes = new { @class = "form-control", @placeholder = "Using name" } })
                                    @Html.ValidationMessageFor(e => e.SupplierID, String.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(e => e.CompanyName, new { @class = "control-label col-md-3" })
                                <div class="col-md-6">
                                    @Html.EditorFor(e => e.CompanyName, String.Empty, new { htmlAttributes = new { @class = "form-control", @placeholder = "Insert Company Name" } })
                                    @Html.ValidationMessageFor(e => e.CompanyName, String.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(e => e.ContactName, new { @class = "control-label col-md-3" })
                                <div class="col-md-6">
                                    @Html.EditorFor(e => e.ContactName, String.Empty, new { htmlAttributes = new { @class = "form-control", @placeholder = "Insert Contact Name" } })
                                    @Html.ValidationMessageFor(e => e.ContactName, String.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(e => e.ContactTitle, new { @class = "control-label col-md-3" })
                                <div class="col-md-6">
                                    @Html.EditorFor(e => e.ContactTitle, String.Empty, new { htmlAttributes = new { @class = "form-control", @placeholder = "Insert Contact Title" } })
                                    @Html.ValidationMessageFor(e => e.ContactTitle, String.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(e => e.Address, new { @class = "control-label col-md-3" })
                                <div class="col-md-6">
                                    @Html.EditorFor(e => e.Address, String.Empty, new { htmlAttributes = new { @class = "form-control", @placeholder = "Insert Address" } })
                                    @Html.ValidationMessageFor(e => e.Address, String.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group ">
                                @Html.LabelFor(e => e.City, new { @class = "control-label col-md-3" })
                                <div class="col-md-6">
                                    @Html.EditorFor(e => e.City, String.Empty, new { htmlAttributes = new { @class = "form-control", @placeholder = "Insert City" } })
                                    @Html.ValidationMessageFor(e => e.City, String.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                @Html.LabelFor(e => e.Region, new { @class = "control-label col-md-3" })
                                <div class="col-md-6">
                                    @Html.EditorFor(e => e.Region, String.Empty, new { htmlAttributes = new { @class = "form-control", @placeholder = "Insert Region" } })
                                    @Html.ValidationMessageFor(e => e.Region, String.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(e => e.PostalCode, new { @class = "control-label col-md-3" })
                                <div class="col-md-6">
                                    @Html.EditorFor(e => e.PostalCode, String.Empty, new { htmlAttributes = new { @class = "form-control", @placeholder = "Insert postal Code" } })
                                    @Html.ValidationMessageFor(e => e.PostalCode, String.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(e => e.Country, new { @class = "control-label col-md-3" })
                                <div class="col-md-6">
                                    @Html.EditorFor(e => e.Country, String.Empty, new { htmlAttributes = new { @class = "form-control", @placeholder = "Insert Country" } })
                                    @Html.ValidationMessageFor(e => e.Country, String.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(e => e.Phone, new { @class = "control-label col-md-3" })
                                <div class="col-md-6">
                                    @Html.EditorFor(e => e.Phone, String.Empty, new { htmlAttributes = new { @class = "form-control", @placeholder = "Insert Phone" } })
                                    @Html.ValidationMessageFor(e => e.Phone, String.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(e => e.Fax, new { @class = "control-label col-md-3" })
                                <div class="col-md-6">
                                    @Html.EditorFor(e => e.Fax, String.Empty, new { htmlAttributes = new { @class = "form-control", @placeholder = "Insert Fax" } })
                                    @Html.ValidationMessageFor(e => e.Fax, String.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(e => e.HomePage, new { @class = "control-label col-md-3" })
                                <div class="col-md-6">
                                    @Html.EditorFor(e => e.HomePage, String.Empty, new { htmlAttributes = new { @class = "form-control", @placeholder = "Insert Home Page" } })
                                    @Html.ValidationMessageFor(e => e.HomePage, String.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" type="submit">Save</button>
                <button class="btn btn-danger" type="button" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
}

NORTHWIND.WebMVC/Views/Suppliers/Index.cshtml
@{
    ViewBag.Title = "Supplier List";
    ViewBag.ModuleName = "Suppliers";
}

@section scripts
{

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    <script type="text/javascript">
    var Apx;
    $(function () {
        Apx = {
            grid: null,
            init: function () {
                this.initGrid();
                $('#actionCreate').on('click', Apx.loadActionCreate);
            },
            initGrid: function () {
                var elm = $('#gridview');
                this.grid = elm.gridView({
                    url: "@Url.Action("Paging", "Suppliers")",
            columns: [
                {
                    header: '', data: 'SupplierID', render: function (data) {
                        return '<a href="#" onclick="showModal(\'' + data +'\')"><span class="fa fa-search"></span></a>\
                                <a href="#" style="color: green; margin-left: 6px;"><span class="fa fa-edit"></span></a>\
                                <a href= "#" style= "color: red; margin-left: 6px;" ><span class="fa fa-trash"></span></a > ';
                    }
                },
                { header: 'Supplier ID', data: 'SupplierID', sortable: true },
                { header: 'Company Name', data: 'CompanyName', sortable: true },
                { header: 'Contact Name', data: 'ContactName', sortable: true },
                { header: 'Contact Title', data: 'ContactTitle', sortable: true },
                { header: 'Address', data: 'Address', sortable: true },
                { header: 'City', data: 'City', sortable: true },
                { header: 'Region', data: 'Region', sortable: true },
                { header: 'Postal Code', data: 'PostalCode', sortable: true },
                { header: 'Country', data: 'Country', sortable: true },
                { header: 'Phone', data: 'Phone', sortable: true },
                { header: 'Fax', data: 'Fax', sortable: true },
                { header: 'Home Page', data: 'HomePage', sortable: true },
            ],
            defaultSortExpression: 'SupplierID'
                })
            },
            gridAction: function (data) {

            },
            loadActionCreate : function (event) {
                event.preventDefault();
                var url = $(this).attr('href');
                $.post(url, function (data) {
                    $('#data-detail').html(data);
                    $('#modal-container').modal();
                })
            },
            AjaxOnSuccess: function (data) {
                if (data !== 'ok') {
                    $('#data-detail').html(data);
                    return;
                }
                $('#modal-container').modal('hide');
                $('#data-detail').html("");
                Apx.grid.reload();
            },
            loadActionCreate2: function (event) {
                event.preventDefault();
                var url = $(this).attr('href');
                $.post(url, function (data) {
                    $('#data-detail2').html(data);
                    $('#modal-container2').modal();
                    $('#modalHeader').html("Editasdasdasadadasdas");
                })
            }
        };
        Apx.init();
    });

    function showModal(data) {
        alert('You click '+data);
    }

    function Delete(data) {
        alert('You click '+data);
    }

    function refresh() {
        gridview.reload();
        }

    function lol() {
            alert("wkwk");
    }
    </script>


}


<div class="col-md-12">
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">Dashboard </h3>
            <div class="btn-group pull-right btn-sm">
                <button type="button" id="actionCreate" class="btn btn-primary" href="@Url.Action("Create","Suppliers")">
                    <i class="glyphicon glyphicon-plus-sign"></i> Add New Suppliers
                </button>
            </div>
        </div>
        <div class="box-body">
            <div id="gridview" style="">
            </div>
        </div>
        <div class="box-footer">
            <button type="button" class="btn btn-primary" onclick="refresh()"><span class="fa fa-refresh"></span> Refresh</button>
        </div>
    </div>
</div>

<div id="modal-container" class="modal fade" data-backdrop="static">
    <div id="data-detail">

    </div>
</div>